Repository Team-Ampersand/GKR-iOS, pull requests merged in 2023-09, with the labels that each got.

#4 🔀 :: [3] tuist setting
  Plugins/GKR/ProjectDescriptionHelpers/Dependency+Project.swift
  Plugins/GKR/ProjectDescriptionHelpers/Dependency+SPM.swift
  Project.swift
  Projects/App/Project.swift
  Projects/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/Contents.json
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/App/Sources/Application/Feature.swift
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Support/Info.plist
  Projects/Feature/Project.swift
  Projects/Service/Project.swift
  Projects/Service/Sources/Services.swift
  Projects/ThirdPartyLib/Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Workspace.swift
Labels: 3️⃣ Priority: Low, ⚙ Type: Setting

#2 🔀 :: Create pull_request_template.md
  .github/pull_request_template.md
Labels: 3️⃣ Priority: Low, ⚙ Type: Setting

#1 🔀 :: Update issue templates
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/😀-todo.md
Labels: 3️⃣ Priority: Low, ⚙ Type: Setting

#6 🔀 :: 외부 라이브러리 주입
  Plugins/GKR/Plugin.swift
  Plugins/GKR/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Feature/Resources/ThirdPartyLib.swift
  Projects/Feature/Sources/ThirdPartyLib.swift
  Projects/ThirdPartyLib/Project.swift
  Projects/ThirdPartyLib/Sources/ThirdPartyLib.swift
  Tuist/Dependencies.swift
Labels: 1️⃣ Priority: High, ⚙ Type: Setting

#8 🔀 :: [7] Create MakeFile
  Makefile
Labels: 2️⃣ Priortiy: Medium, ⚙ Type: Setting
